version: '2'
 
services:
  php:
      build: ./docker/php
      restart: always
      volumes: 
         - ./:/var/www/html
      ports : 
         - 8005:80
      depends_on : 
      - db
  db:
    build : ./docker/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80
volumes:
  dbdata: